# Generated by Django 5.2.7 on 2025-10-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('study', 'Study'), ('tech', 'Tech'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
