# Generated by Django 5.2.7 on 2025-10-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='profiles/'),
        ),
    ]
